### ISSUE TITLE
Control stop order in timetables

### ISSUE THREAD

**Issue by aaronantrim** [brendannee/gtfs-to-html#10]
Need: Control stop order manually. This is especially important if #9 (multi-route timetables) is implemented.

Proposal: Add a new file called timetable_stop_order with the following fields:
* timetable_id
* stop_id
* stop_sequence

With multi-route timetables, stop order could not be controlled deliberately using stop_times.stop_sequence.

**Comment by brendannee** [comment]
An update is live that lets you add a `timetable_stop_order.txt` file as you proposed above.  If provided, this file dictates the stops shown the timetable.

Details on this are live in the readme: https://github.com/brendannee/gtfs-to-html
