### ISSUE TITLE
Include city names in timetables

### ISSUE THREAD

**Issue by antrim** [brendannee/gtfs-to-html#11]
Via @siwood

Timetables for intercity transit routes often indicate city names. e.g. http://sctransit.com/maps-schedules/route-38/

@trilliumtransit can change our export process so that we add a stops.city field.
Or, we already export a stop_attributes.txt field GTFS+ (Extended) feeds for the MTC, which can also be used. Example: http://transitfeeds.com/p/sonoma-county-transit/419/latest/file/stop_attributes.txt

**Comment by brendannee** [comment]
We can use stop_attributes.txt - where in the timetable should city appear?  Should it be `${stop_name}, ${city}` when a city is available?

**Comment by brendannee** [comment]
I pushed an update to node-gtfs to parse `stop_attributes.txt` and handle `stop_city` and an update to gtfs-to-html to have the option `stopStopCity`.

https://github.com/brendannee/gtfs-to-html#showstopcity

Now, you can get stop city printed before each group of stops for that city, similar to the existing Sonoma Transit schedules. Here is an example of the output:

<img width="859" alt="screen shot 2016-12-04 at 3 30 37 am" src="https://cloud.githubusercontent.com/assets/96217/20863706/0764f85c-b9d4-11e6-9a5f-cc365277da99.png">

Let me know if there are other places that city should be incorporated, and if there are any other fields in stop_attributes.txt that could be useful elsewhere.
