### ISSUE TITLE
Easier-to-read filenames

### ISSUE THREAD

**Issue by antrim** [brendannee/gtfs-to-html#12]
current form is timetableId_longname_serviceLabel_directionId e.g. 38_NorthernRohnertParkTripper_NewSchoolServiceCalendar_0

Example form which would be easier for humans to distinguish:
timetableId_shortName/longName_directionLabel {some declaration of service days}

**Comment by brendannee** [comment]
I updated the filename format to be:

The filename is currently set to use fields specified in timetables.txt

if direction ID is specified in timetables.txt:
routeShortName_directionId_serviceDayIndication.html

if no direction ID specified in timetables.txt:
routeShortName_serviceDayIndication.html

Some example filenames generated for Sonoma County are:

14T_0_mon-fri.html
14T_0_mon-tues,thur-fri.html
14T_0_wed.html
12T_0_mon-fri.html
12T_0_mon-tues,thur-fri.html
12T_0_wed.html
14_0_mon-fri.html
12_0_mon-fri.html
12_0_sat.html

@antrim Let me know what you think.

**Comment by antrim** [comment]
@brendannee : This is nice to read for Sonoma but I worry that this will break in a few situations:
* For routes w/o short name
* Cases where there is an upcoming service change (i.e. Two Route 12 Mon-Fri schedules, one current, and the other going into service in two weeks)
* Lack of timetable_id means that we lose the opportunity to quickly look up corresponding records in timetables.txt or use software that automatically reads in timetables.txt and lines it up with the timetables (this is something that I believe we currently do with some WordPress websites)

**Comment by thomastrillium** [comment]
also maybe we should think forward to a solution that incorporates implications `timetable_pages.txt` #17

**Comment by brendannee** [comment]
@antrim Thanks for the feedback.

I added back in timetable_id and use `route_long_name` if `route_short_name` is not set.

Here are some example filenames, including a few where I made the `route_short_name` blank:
36_42_1_mon-fri.html
35_42_0_mon-fri.html
34_RussianRiverArea,SantaRosa_1_mon-fri.html
33_RussianRiverArea,SantaRosa_0_mon-fri.html
32_20_1_mon-fri.html
31_20_1_sat-sun.html
30_20_0_mon-fri.html
29_20_0_sat-sun.html
28_14T_0_mon-fri.html
27_14T_0_mon-tues,thur-fri.html

@thomastrillium To handle timetable pages, we could require that a filename be specified in `timetable_pages.txt` and just use that.

**Comment by thomastrillium** [comment]
agreed on `timetable_filename` or other such field.
