### ISSUE TITLE
Reduce wrapping for the "headless" option; or offer a "just timetables" option

### ISSUE THREAD

**Issue by antrim** [brendannee/gtfs-to-html#15]

**Comment by brendannee** [comment]
I found an issue with the way arguments were getting parsed.  Now, you can get proper "headless" output by running

`npm run gtfs-to-html -- --nohead`

Does this solve this issue, or did you have something else in mind?  It should be pretty easy to support many different options to customize the output, so just let me know if you have other ideas.

**Comment by brendannee** [comment]
Closing this issue, as it should be solved with the 

`npm run gtfs-to-html -- --nohead` command.
