### ISSUE TITLE
Timetable pages grouping multiple timetables

### ISSUE THREAD

**Issue by thomastrillium** [brendannee/gtfs-to-html#17]
an agency can feasibly use the html output direct from gtfs-to-html as the "route page" on their website, although this likely wouldn't be advisable currently unless budgets were very small.

however, such agencies likely want a "route 2" page, as opposed to 4 different pages for each direction/weekday vs. weekend.

A tool grouping various timetables together as separate tables within the same file and body tag could make the direct outputs more immediately usable by some agencies.

**Comment by brendannee** [comment]
Great idea.

Do you think we should have a new file to control this? `timetable_groups.txt` or `pages.txt` that specifies an array of ids from `timetables.txt`? Or do you have a different method of specifying this in mind?

**Comment by thomastrillium** [comment]
i was thinking just a `timetable_group_id` within `timetables.txt`, but now that you mention it, i guess it might make more sense to make a `timetable_groups.txt` so that we could consider later on providing various attributes, e.g. (just ideas off the top of my head not for implementation) timetable_group_sequence and timetable_map_id to define what order the timetables go in in the html, and what map(s) should appear on the page (don't need one for every timetable).

**Comment by brendannee** [comment]
I like the idea of having another file to specify this, is `timetable_groups.txt` the correct name?  Or `timetable_pages.txt`? or `pages.txt`?

Does this mean that all users of gtfs-to-html need to have both a timetables.txt and a timetable_groups.txt?

**Comment by thomastrillium** [comment]
my preference would be for `timetable_pages.txt` as an optional field, but required is fine if that's quicker/better.

i imagine it's simple enough to make this optional, so that if it is just one timetable per page the agency can ignore. that situation is definitely common at small agencies where all routes are loops and only operate M-F.

so, i imagine, no `timetable_pages.txt` = current functionality (but ideally still allowing options like "nohead" etc.)

however, if that's more difficult/costly because you would need to program for both instances, then i don't think it's a big burden to force people to make a file that would just have two columns with 'timetable_id' and 'timetable_page_id' as the same value, and we could make it required.

**Comment by brendannee** [comment]
I just pushed a large change to support timetable_pages.txt.

`timetable_pages.txt` is an optional file that allows grouping timetables together on a single page.  If you don't supply this file, a "timetable page" will get created for each entry in `timetables.txt`

`timetables.txt` now has two new fields, `timetable_page_id` and `timetable_sequence`.

`timetable_page_id` is the id of the timetable_page that the timetable belongs to, and `timetable_sequence` is the order on the page that it should show up.

`timetable_pages.txt` has 3 fields: `timetable_page_id`, `route_label`, `filename`.

`route_label` shows up at the top of the page, and `filename` is the name of the file that is generated.  Both are required.

The version of timetables.txt and timetable_pages.txt that I used are attached, so you can generate output like the html file inside the attached `cloverdale.zip` (github issues doesn't allow html attachments)

[timetable_pages.txt](https://github.com/brendannee/gtfs-to-html/files/494509/timetable_pages.txt)
[timetables.txt](https://github.com/brendannee/gtfs-to-html/files/494510/timetables.txt)
[cloverdale.html.zip](https://github.com/brendannee/gtfs-to-html/files/494511/cloverdale.html.zip)

There are likely a lot of config options and additional fields to timetable_pages.txt that we could implement to help control the way the output looks, so please let me know what you think would be useful.

**Comment by brendannee** [comment]
Also, now would be a good time to change any of the new field or filenames I proposed if you have a suggestion on how to improve them. Once we start using them, there will be more friction in changing them, but right now it is pretty easy.

**Comment by brendannee** [comment]
A headsup for testing the latest code, I pushed an update to node-gtfs that changes the format of the config file and also pushed an update to gtfs-to-html.  You'll need to make your config file JSON now, and call it config.json not config.js.

**Comment by brendannee** [comment]
@thomastrillium `timetable_pages.txt` should now be working - do you have an agency that you would like to test this with?
