### ISSUE TITLE
Route alignments/shapes on maps

### ISSUE THREAD

**Issue by thomastrillium** [brendannee/gtfs-to-html#18]
The maps currently only provide stop locations. Is it feasible to include alignments as well, or does this become too much data to load when shapes are long/contain too many points?

**Comment by brendannee** [comment]
I pushed an update to node-gtfs to better support dealing with shapes, and an update to gtfs-to-html to show shapes on the map if they are available.

For the map, I search for all shapes that match any of the service_ids specified via timetables.txt (using days of the week) so you can have more than one shape show up for a specific timetable. See Sonoma County route 26 - Sebastopol, Cotati, Rohnert Park for an example of where there are a few different shapes for one timetable.

I suspect there are lot of improvements to the map component and ways that different agencies would want to customize the map output. Please open new issues as you think of these.
