### ISSUE TITLE
Better format for listing days "service not provided on"

### ISSUE THREAD

**Issue by brendannee** [brendannee/gtfs-to-html#19]
Currently, there is a list of dates like:

Service not provided on:
Mon, Jul 4, 2016
Mon, Sep 5, 2016
Thu, Nov 24, 2016
Fri, Nov 25, 2016
Sat, Dec 24, 2016
Sun, Dec 25, 2016
Sat, Dec 31, 2016

These could be grouped to make them more concise and take up less space:

Service not provided on:
Jul 4, Sep 5, Nov 24-25, Dec 24-25, Dec 31, 2016

@antrim What do you think? Do you have a better suggested format?

**Comment by trilliumtransit** [comment]
That's terrific!

Also, it wouldn't be hard for us to add a GTFS field in calendar_dates.txt,
holiday_name, if that could support further utility for this feature (now
or later).

**Comment by thomastrillium** [comment]
I really like the holiday_name feature idea.

**Comment by brendannee** [comment]
`holiday_name` could work and wouldn't be too hard to implement, but I'd need to add it as an optional field to the node-gtfs library for it to get imported. Since we'd still need to list the actual dates (no one really knows exactly when easter or thanksgiving falls) is it worth having a custom field for this?

**Comment by thomastrillium** [comment]
I'm not sure I agree. Well, I agree that no one knows when easter or thanksgiving falls ahead of time. But I think that some one is considerably more likely to remember on Thanksgiving that there's no service if they're told there's no service on thanksgiving as opposed to on november 24.

**Comment by brendannee** [comment]
Good point - if you think it would be valuable to be able to name holidays, lets implement it. Would the output then look like:

Service not provided on:
Independence Day (Jul 4), Labor Day (Sep 5), Thanksgiving (Nov 24-25), Christmas (Dec 24-25), New Years (Dec 31)

What is the best way to indicate the year?  Put it after each date?

Let me know if you have a better idea for the exact formatting.

**Comment by thomastrillium** [comment]
My thought:

if `holiday_name` exists: then just Independence Day, Labor Day, Thanksgiving, Day after Thanksgiving, Christmas Eve, Christmas, New Years Eve

if `holiday_name` doesn't exist, then as you suggested above: Jul 4, Sep 5, Nov 24-25, Dec 24-25, Dec 31, 2016

**Comment by brendannee** [comment]
I pushed an update to support holiday_name in node-gtfs and an update to use it in gtfs-to-html.

Here is a modifed calendar_dates.txt for Sonoma County that you can use to see this new feature in action. [calendar_dates.txt](https://github.com/brendannee/gtfs-to-html/files/490209/calendar_dates.txt)

The output for Route 22 is 

`Service not provided on: Fourth of July, Sep 5, 2016, Thanksgiving, Christmas, Christmas Eve, Christmas, New Years Eve`

Let me know what you think.

**Comment by antrim** [comment]
calendar_dates.holiday_name will start showing up in new Trillium GTFS feeds now.
