### ISSUE TITLE
Improved Error Reporting

### ISSUE THREAD

**Issue by NomeQ** [brendannee/gtfs-to-html#20]
Enhancement request: verbose option for error reporting, help indicate when errors come from gtfs data, especially incorrectly built timetables.txt

**Comment by brendannee** [comment]
Can you give me an example GTFS with errors (or a few examples) that I can use for testing?

**Comment by NomeQ** [comment]
I will look for some more examples, since this won't be the most helpful for testing, but this request was inspired by working on [trinity-ca-us.zip](https://github.com/brendannee/gtfs-to-html/files/522810/trinity-ca-us.zip) and having trouble determining if it was a GTFS error or a GTFS-to-HTML error. (It appears to be a GTFS error but still uncertain; Trinity has very limited service that isn't particularly compatible with GTFS-to-HTML).

> TypeError: Cannot read property 'length' of undefined
>     at gtfs.getStoptimesByTrip (/Users/Nome/Documents/trillium/gtfs-to-html/lib/utils.js:337:42)

[npm-debug.txt](https://github.com/brendannee/gtfs-to-html/files/522830/npm-debug.txt)

**Comment by brendannee** [comment]
I pushed an update that has better error handling, so may be able to sort this out.

https://github.com/brendannee/gtfs-to-html/files/522810/trinity-ca-us.zip doesn't have a timetables.txt file in it, and the timetables-new.txt seems out of date (service Ids don't match the rest of the GTFS).

Please reopen this issue if you are still having problems and link to an updated trinity version with an up-to-date timetables.txt
