### ISSUE TITLE
Most Recent Commits Not Working

### ISSUE THREAD

**Issue by NomeQ** [brendannee/gtfs-to-html#21]
The feed at http://data.trilliumtransit.com/gtfs/petalumatransit-petaluma-ca-us/petalumatransit-petaluma-ca-us.zip builds timetables at commit 801a13a, but fails under recent commits with 

> TypeError: Cannot read property 'length' of undefined
>     at gtfs.getStoptimesByTrip (/Users/Nome/Documents/trillium/gtfs-to-html/lib/utils.js:337:42)

Logfile: [npm-debug.txt](https://github.com/brendannee/gtfs-to-html/files/520606/npm-debug.txt)

**Comment by brendannee** [comment]
I just pushed an update that should solve this issue and added better error messages.

In the case of the GTFS at http://data.trilliumtransit.com/gtfs/petalumatransit-petaluma-ca-us/petalumatransit-petaluma-ca-us.zip - it has a timetable rule that refers to a route_id that does exist - when you run it with the latest version of gtfs-to-html you should get:

`Error: No route found for route_id=2048, timetable_id=15`

Also, the start_date and end_date for this GTFS file in timetables.txt are off by a year - they don't match any service_ids.
