### ISSUE TITLE
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode

### ISSUE THREAD

**Issue by nselikoff** [brendannee/gtfs-to-html#22]
Hey there, I've cloned and set up the repo + mongodb, but when I `npm run gtfs-to-html` I'm getting the following error:

````
/gtfs-to-html/scripts/gtfs-to-html.js:26
    let timetablePages;
    ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:974:3
````

I'm on node 4.6.1, npm 3.10.9. I've tried running the script with node directly using `--use_strict` but that breaks some of the other dependencies.

**Comment by nselikoff** [comment]
I get much further with node 6.9.1, so maybe it's just a matter of updating package.json and/or adding a .node_version file in the root of the project?

**Comment by brendannee** [comment]
Yes, this is an issue with the older version of node - so I updated the required version in package.json.

6.9.1 should work great.
