### ISSUE TITLE
Add timetable output messages - # of trips, routes, patterns, stops, etc.

### ISSUE THREAD

**Issue by antrim** [brendannee/gtfs-to-html#23]
Feature request: When the GTFS-to-HTML software runs, add to the output messages with some statistics about each timetable, e.g. number of:

- routes
- directions
- trips
- patterns
- stops and/or timepoints

This provides a high-level report to quickly "sanity check" output (and compare to previous outputs).

**Comment by brendannee** [comment]
I pushed an update that prints some stats after each run - see screenshot
<img width="860" alt="screen shot 2016-11-30 at 7 32 41 am" src="https://cloud.githubusercontent.com/assets/96217/20742244/48f14242-b6cf-11e6-8067-181e37bd92ad.png">

Let me know what you think.
