### ISSUE TITLE
Standardize option format

### ISSUE THREAD

**Issue by brendannee** [brendannee/gtfs-to-html#26]
@thomastrillium @antrim Now that gtfs-to-html has a bunch of options, I'd like to standardize how they are formatted.

These are the key names for the options in config.json, listed here: https://github.com/brendannee/gtfs-to-html#configuration

Which do you think is best? camelCase, underscore_case or ALL_CAPS

And, while things are being changed, can you think of better names for any of them?

**Comment by thomastrillium** [comment]
Personally I prefer camelCasing. The only thing I can think of that would make me prefer underscore would be that the GTFS spec uses underscore.

I think all the titles are as clear as they can be. The only one I'd question would be verbose, which could be "printOutput" or "printResults". But that only matters to someone who really knows what they're doing (and to whom output matters), so if "verbose" is standard for this functionality, then I think it should be left alone too.

**Comment by antrim** [comment]
Looks great.

**Comment by brendannee** [comment]
Options for node-gtfs and gtfs-to-html are now all camelCase - you'll need to update your config.json files to work with the latest version.
