### ISSUE TITLE
Printing Code Snippets in HTML

### ISSUE THREAD

**Issue by trilliumtransit** [brendannee/gtfs-to-html#29]
With the most recent version, I have been getting code printed in the HTML itself, e.g.
`col class="run_#{idx} #{(trip.trip_short_name) ? 'trip_short_name_' + trip.trip_short_name : ''}" id="trip_id_#{trip.trip_id}">`
Additionally, on this GTFS data a lot of stop times were missing beyond the first row and marked as *No Service at this Timepoint.*

I rolled back to a much earlier commit (from the config.js era of GTFS-to-HTML) and it was able to correctly parse the GTFS and produced accurate timetables. I've attached the GTFS data in question as well as the same timetable produced both by the current version and the old version.
[nwconnector-or-us.zip](https://github.com/brendannee/gtfs-to-html/files/784464/nwconnector-or-us.zip)
[timetables.zip](https://github.com/brendannee/gtfs-to-html/files/784469/timetables.zip)

**Comment by brendannee** [comment]
I think this is from a template file from a much older version, this line has been updated https://github.com/brendannee/gtfs-to-html/blob/master/views/timetablepage.pug#L26

Try deleteing your gtfs-to-html and reinstalling, including the global version if you have one:

npm uninstall gtfs-to-html -g
