### ISSUE TITLE
no time table

### ISSUE THREAD

**Issue by yannick-b** [brendannee/gtfs-to-html#6]
how can i trouble shoot missing time table?. I get the list of route but that s it.

**Comment by brendannee** [comment]
Sorry about that - I just updated the readme with info about timetables.txt - a required additional file to add to your GTFS that controls how schedules are built: https://github.com/brendannee/gtfs-to-html

This file allows you to create timetables for different days of the week, for example a timetable for weekdays and another one for weekends for the same route and direction.
