### ISSUE TITLE
Show timetable_id in the exported timetables

### ISSUE THREAD

**Issue by aaronantrim** [brendannee/gtfs-to-html#7]
We (Trillium) are interested in a change where timetable ID would be prepended to the filenames of the HTML timetables. This would help sync up with information in timetables.txt. This will be used in a WordPress extension that loads timetables.

**Comment by brendannee** [comment]
This is done: https://github.com/brendannee/gtfs-to-html/commit/dded8730aeabf5f1116f726c2160edbb560158f4
