### ISSUE TITLE
Add support for stop_times.timepoint

### ISSUE THREAD

**Issue by aaronantrim** [brendannee/gtfs-to-html#8]
Goal: Produce a more concise timetable that shows timepoints only.

Request: If specified in a configuration file, only show stops for cases where stop_times.timepoint == 1 (https://developers.google.com/transit/gtfs/reference?hl=en#stop_times_fields).

**Comment by brendannee** [comment]
I pushed an update that should obey this, documentation is updated to show where in config.json to put the option.

Let me know if it doesn't work as expected, and which agencies you are testing it with.
